parameters:
  - name: BuildPool
    type: string
    default: 'ubuntu-latest'

resources:
  repositories:
    - repository: TfTemplates
      name: andrewtyped/aztf.pipelinetemplates
      type: github
      ref: refs/heads/main
      endpoint: github.com_andrewtyped

extends:
  template: /tf/tf-azure-pipeline.yml@TfTemplates
  parameters:
    BuildPool: ${{ parameters.BuildPool }}
    AzureArmServiceConnection: rg-root-1-deployer
    DeploymentEnvironment: TfEnv
    VariableGroups:
      - aztf.subscriptionroot
    TfPlanApplyArgs: " -var 'azure_tenant_id=$ENV:AZURE_TENANTID' -var 'azure_devops_org=$(System.CollectionUri)' -var 'azure_devops_pat=$(Azure_DevOps_Pat)' "